import { createTemplateSet } from "../shared/createTemplateSet";

const templates = createTemplateSet({
  folder: "ecommerce-store",
  niche: "Ecommerce Store",
  terms: [
    "product catalog",
    "cart and checkout",
    "customer favourites",
    "store inventory",
  ],
  palettes: [
    ["#f8fafc", "#2563eb", "#111827"],
    ["#fff7ed", "#ea580c", "#1f2937"],
    ["#f0fdf4", "#16a34a", "#111827"],
    ["#fdf2f8", "#db2777", "#18181b"],
    ["#f5f3ff", "#7c3aed", "#111827"],
  ],
  variants: [
    {
      slug: "market-grid",
      title: "FreshCart Market",
      layout: "bentoGrid",
      layoutName: "Market Grid",
      pages: [
        {
          id: "home",
          label: "Home",
          path: "/",
          eyebrow: "Online grocery storefront",
          title: "Fresh products, fast cart, clean buying flow",
          summary: "A modern ecommerce home page for grocery sellers with hero deals, categories, cart, favourites, and product image slots.",
          blocks: ["product catalog", "cart and checkout", "customer favourites"],
        },
        {
          id: "shop",
          label: "Shop",
          path: "/shop",
          eyebrow: "Shop page",
          title: "Browse products by category and availability",
          summary: "A catalog page ready for products, images, prices, inventory, favourites, and cart actions.",
          blocks: ["store inventory", "product catalog", "cart and checkout"],
        },
        {
          id: "deals",
          label: "Deals",
          path: "/deals",
          eyebrow: "Deals page",
          title: "Promote bundles, fresh arrivals, and daily offers",
          summary: "A deal-focused page for grocery bundles, seasonal produce, and popular product groups.",
          blocks: ["customer favourites", "store inventory", "product catalog"],
        },
        {
          id: "account",
          label: "Account",
          path: "/account",
          eyebrow: "Customer page",
          title: "Customer details, favourites, and saved carts",
          summary: "A customer page compatible with backend buyer profiles, carts, and favourite products.",
          blocks: ["customer favourites", "cart and checkout", "store inventory"],
        },
        {
          id: "contact",
          label: "Contact",
          path: "/contact",
          eyebrow: "Store support",
          title: "Delivery, support, and store contact details",
          summary: "A contact page for delivery address, customer phone, email, and order support.",
          blocks: ["cart and checkout", "customer favourites", "product catalog"],
        },
      ],
    },
    {
      slug: "split-catalog",
      title: "Daily Basket",
      layout: "splitHero",
      layoutName: "Split Catalog",
      pages: [
        {
          id: "home",
          label: "Home",
          path: "/",
          eyebrow: "Storefront starter",
          title: "A premium shop front for everyday products",
          summary: "A clean ecommerce layout with product cards, uploadable images, live cart controls, and customer collection points.",
          blocks: ["product catalog", "store inventory", "cart and checkout"],
        },
        {
          id: "shop",
          label: "Shop",
          path: "/shop",
          eyebrow: "Catalog",
          title: "Products organized for quick buying",
          summary: "A shop page built for grocery, fashion, pharmacy, bakery, or any small online store.",
          blocks: ["product catalog", "customer favourites", "store inventory"],
        },
        {
          id: "orders",
          label: "Orders",
          path: "/orders",
          eyebrow: "Customer flow",
          title: "Cart and buyer data ready for checkout",
          summary: "A page structure for customer details, cart state, favourites, and purchase readiness.",
          blocks: ["cart and checkout", "customer favourites", "store inventory"],
        },
        {
          id: "about",
          label: "About",
          path: "/about",
          eyebrow: "Store story",
          title: "Build trust before the customer checks out",
          summary: "A story page for quality, sourcing, delivery promises, and local store proof.",
          blocks: ["store inventory", "product catalog", "customer favourites"],
        },
        {
          id: "support",
          label: "Support",
          path: "/support",
          eyebrow: "Help",
          title: "Clear support for deliveries and product questions",
          summary: "A support page for contact forms, delivery areas, and customer service information.",
          blocks: ["cart and checkout", "product catalog", "store inventory"],
        },
      ],
    },
    {
      slug: "deal-led-store",
      title: "QuickMart Direct",
      layout: "editorialStack",
      layoutName: "Deal Led Store",
      pages: [
        {
          id: "home",
          label: "Home",
          path: "/",
          eyebrow: "Daily deals",
          title: "Push best sellers and offers above the fold",
          summary: "A conversion-first ecommerce page for discounts, bundles, and high-demand product cards.",
          blocks: ["cart and checkout", "product catalog", "store inventory"],
        },
        {
          id: "shop",
          label: "Shop",
          path: "/shop",
          eyebrow: "Products",
          title: "A fast catalog for repeated buying",
          summary: "A shop surface for search, categories, product images, favourites, and cart quantity controls.",
          blocks: ["product catalog", "customer favourites", "cart and checkout"],
        },
        {
          id: "favourites",
          label: "Favourites",
          path: "/favourites",
          eyebrow: "Saved products",
          title: "Bring customers back to products they liked",
          summary: "A favourites page compatible with saved product IDs from the backend.",
          blocks: ["customer favourites", "product catalog", "store inventory"],
        },
        {
          id: "delivery",
          label: "Delivery",
          path: "/delivery",
          eyebrow: "Fulfillment",
          title: "Show delivery areas, timing, and fees clearly",
          summary: "A delivery page for customer address collection and order support.",
          blocks: ["store inventory", "cart and checkout", "customer favourites"],
        },
        {
          id: "contact",
          label: "Contact",
          path: "/contact",
          eyebrow: "Support",
          title: "Keep customers close to store support",
          summary: "A contact page for order questions, delivery support, and local store details.",
          blocks: ["cart and checkout", "customer favourites", "product catalog"],
        },
      ],
    },
    {
      slug: "category-first",
      title: "ShelfFlow Store",
      layout: "sideRail",
      layoutName: "Category First",
      pages: [
        {
          id: "home",
          label: "Home",
          path: "/",
          eyebrow: "Category storefront",
          title: "Lead with categories, then sell with product cards",
          summary: "A category-led ecommerce template for grocery sellers and product-heavy stores.",
          blocks: ["store inventory", "product catalog", "cart and checkout"],
        },
        {
          id: "categories",
          label: "Categories",
          path: "/categories",
          eyebrow: "Browse",
          title: "Group products so customers find them faster",
          summary: "A categories page for produce, dairy, pantry, bakery, household, or custom collections.",
          blocks: ["product catalog", "store inventory", "customer favourites"],
        },
        {
          id: "cart",
          label: "Cart",
          path: "/cart",
          eyebrow: "Checkout prep",
          title: "Review quantities before checkout",
          summary: "A cart page structure matching product, quantity, snapshot price, and customer data.",
          blocks: ["cart and checkout", "customer favourites", "store inventory"],
        },
        {
          id: "profile",
          label: "Profile",
          path: "/profile",
          eyebrow: "Customer",
          title: "Collect buyer details for this store",
          summary: "A customer profile page for name, phone, email, address, favourites, and cart recovery.",
          blocks: ["customer favourites", "cart and checkout", "product catalog"],
        },
        {
          id: "support",
          label: "Support",
          path: "/support",
          eyebrow: "Help",
          title: "Answer product and delivery questions",
          summary: "A support page for store policies, contact details, and delivery help.",
          blocks: ["store inventory", "cart and checkout", "customer favourites"],
        },
      ],
    },
    {
      slug: "premium-shop",
      title: "Prime Pantry",
      layout: "galleryHero",
      layoutName: "Premium Shop",
      pages: [
        {
          id: "home",
          label: "Home",
          path: "/",
          eyebrow: "Premium ecommerce",
          title: "A polished store for products with strong visuals",
          summary: "A premium ecommerce layout where every product can use uploaded images and clean catalog details.",
          blocks: ["product catalog", "customer favourites", "store inventory"],
        },
        {
          id: "shop",
          label: "Shop",
          path: "/shop",
          eyebrow: "Catalog",
          title: "Show products with clean media and pricing",
          summary: "A product grid ready for image uploads, pricing, inventory, tags, and categories.",
          blocks: ["product catalog", "store inventory", "cart and checkout"],
        },
        {
          id: "collections",
          label: "Collections",
          path: "/collections",
          eyebrow: "Collections",
          title: "Sell bundles and curated product groups",
          summary: "A collections page for grocery bundles, weekly picks, and featured store offers.",
          blocks: ["store inventory", "product catalog", "customer favourites"],
        },
        {
          id: "checkout",
          label: "Checkout",
          path: "/checkout",
          eyebrow: "Buyer flow",
          title: "Prepare customer and cart data for payment",
          summary: "A checkout-ready page with buyer fields, cart summary, and saved favourites.",
          blocks: ["cart and checkout", "customer favourites", "store inventory"],
        },
        {
          id: "contact",
          label: "Contact",
          path: "/contact",
          eyebrow: "Store contact",
          title: "Make support and delivery questions easy",
          summary: "A support page for local store contact, delivery instructions, and customer requests.",
          blocks: ["customer favourites", "cart and checkout", "product catalog"],
        },
      ],
    },
  ],
});

export default templates;
